ENTRY(_start)

SECTIONS
{
    . = 1M;

    PROVIDE(KERNEL_START = .);
    .text BLOCK(4K) : ALIGN(4K)
    {
        *(.multiboot)
        *(.text)
    }

    .rodata BLOCK(4K) : ALIGN(4K)
    {
        *(.rodata)
    }

    .data BLOCK(4K) : ALIGN(4K)
    {
        *(.data)
    }

    .bss BLOCK(4K) : ALIGN(4K)
    {
        *(COMMON)
        *(.bss)
    }

    .phony : {

    }
    PROVIDE(KERNEL_END = .);
}
